import 'dart:math';

class NameSuggestions {
  static const List<String> adjectives = [
    'hurtig',
    'frisk',
    'snabb',
    'hälsosam',
    'omtänksam',
    'aktiv',
    'energisk',
    'stark',
    'uthållig',
    'pigg',
    'flitig',
    'spänstig',
    'modig',
    'alert',
    'rörlig',
    'spännande',
    'vältränad',
    'smidig',
    'sportig',
    'vital',
    'glad',
    'social',
    'kamratlig',
    'äventyrlig',
    'positiv',
    'nyfiken',
    'peppad',
    'tålmodig',
    'fokuserad',
    'målmedveten',
    'balanserad',
    'naturnära',
    'inspirerande',
    'trygg',
    'rolig',
    'hjälpsam',
    'respektfull',
    'samverkande',
    'entusiastisk',
    'livlig',
    'harmonisk',
    'petig',
    'finurlig',
    'klok',
    'kreativ',
    'uppfinningsrik',
    'medelmåttig',
    'konstig',
    'vilsen',
    'yr',
    'snurrig',
    'klumpig',
    'slö',
    'lat',
    'trött',
    'slapp',
    'gullig',
    'snygg',
    'söt',
    'bortkommen',
    'sund',
    'sur',
    'arg',
    'sprallig',
    'sömnig',
    'trött',
    'slemmig',
    'kladdig',
    'lerig',
    'blöt',
    'varm',
    'kall',
    'ljus',
    'mörk',
    'blå',
    'grön',
    'osynlig',
    'synlig',
    'spöklik',
    'annorlunda',
    'pytteliten',
    'smutsig',
    'vettskrämd',
    'feg',
    'helensk',
    'sjuk',
    'nykommen',
  ];

  static const List<String> nouns = [
    'volleyboll',
    'trampolin',
    'gympasal',
    'löpare',
    'klättrare',
    'cyklist',
    'simmare',
    'friidrottare',
    'vandring',
    'träning',
    'joggare',
    'gymnast',
    'basket',
    'badminton',
    'kanot',
    'orientering',
    'motion',
    'rörelse',
    'styrka',
    'lägereld',
    'kompass',
    'ryggsäck',
    'tält',
    'tältpinne',
    'tältare',
    'skog',
    'fjäll',
    'stig',
    'flugsvamp',
    'bärplockare',
    'friluftsliv',
    'gemenskap',
    'samarbete',
    'kost',
    'näring',
    'måltid',
    'grillning',
    'picknick',
    'utflykt',
    'äventyr',
    'paddling',
    'klättring',
    'cykling',
    'simning',
    'yoga',
    'friidrott',
    'jogging',
    'gymnastik',
    'basketboll',
    'badmintonspel',
    'paddlare',
    'forsränning',
    'gummibåt',
    'papegoja',
    'orienterare',
    'motionsspår',
    'styrketräning',
    'gym',
    'nyårskurs',
    'riksläger',
    'ungdomsträff',
    'påskkurs',
    'badare',
    'bastubadare',
    'bastu',
    'spökboll',
    'spökfisk',
    'spöke',
    'skugga',
    'husvagn',
    'ost',
    'kruska',
    'sten',
    'stund',
    'skatt',
    'mjölk',
    'fiskebåt',
    'fiskespö',
    'krok',
    'segelbåt',
    'säl',
    'skärgård',
    'fisk',
    'mås',
    'fiskmås',
    'berg',
    'basläger',
    'sång',
    'kram',
    'skämt',
    'grill',
    'spel',
    'leksak',
    'grönkål',
    'spenat',
    'broccoli',
    'morot',
    'ärta',
    'lera',
    'snö',
    'snöskoter',
    'snöboll',
    'hammare',
    'skruvmejsel',
    'såg',
    'diskränna',
    'bajamaja',
    'myggbett',
    'ordförande',
    'sekreterare',
    'kassör',
    'busschafför',
    'justerare',
    'kanslist',
    'medlem',
    'knatte',
    'knattekamp',
    'mångkamp',
    'enhjuling',
    'jonglör',
    'orienterare',
    'cheerleader',
    'fästing',
    'spökrunda',
    'simsträcka',
    'hinderbana',
    'brygga',
    'snabblopp',
    'dansbana',
    'disco',
    'krypta',
    'folkhögskola',
    'styrelse',
    'lägerbål',
    'tablå',
    'lek',
    'ungdomstält',
    'mugglare',
    'quidditch',
    'sallad',
    'lägerprogram',
    'bok',
    'slottsspöke',
    'växtform',
    'dröm',
    'vikingaskepp',
    'båtbyggeri',
    'paviljong',
    'fotbollsplan',
    'volleybollplan',
    'kaffekopp',
    'knatteköping',
    'lergrop',
    'rektor',
    'mats',
    'smoothie',
  ];

  // random suggestion
  static String generateSuggestion() {
    final random = Random();

    final adjective = adjectives[random.nextInt(adjectives.length)];
    final noun = nouns[random.nextInt(nouns.length)];
    final number = random.nextInt(100).toString().padLeft(2, '0');

    // Capitalize the first letter of both adjective and noun
    final capitalizedAdjective =
        adjective[0].toUpperCase() + adjective.substring(1);
    final capitalizedNoun = noun[0].toUpperCase() + noun.substring(1);

    return '$capitalizedAdjective$capitalizedNoun$number';
  }

  // generate many
  static List<String> generateMultipleSuggestions(int count) {
    final suggestions = <String>[];

    for (var i = 0; i < count; i++) {
      suggestions.add(generateSuggestion());
    }

    return suggestions;
  }
}
